name: Export Secrets to Env

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Env File
        run: |
          cat << 'EOF' > my_secrets.env
          SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}
          ALERT_EMAIL_SENDER=${{ secrets.ALERT_EMAIL_SENDER }}
          ALERT_EMAIL_PASSWORD=${{ secrets.ALERT_EMAIL_PASSWORD }}
          ALERT_EMAIL_RECEIVER=${{ secrets.ALERT_EMAIL_RECEIVER }}
          SENDER_NAME=${{ secrets.SENDER_NAME }}
          REG_SA_KEY='${{ secrets.REG_SA_KEY }}'
          EOF

      - name: Upload Env Artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-artifact
          path: my_secrets.env
